#!/usr/bin/env bash

function install {
    yarn install
}

function build {
    yarn run build
}

function watch {
    yarn run watch
}

function format {
    yarn run format
}

function t {
    test_lib node js
}

function docs {
    mkdir -p docs/api &&
        npx typedoc src --out docs/api/formal-concept --mode modules --ignoreCompilerErrors
}

function test_lib {
    prog=$1
    ext=$2

    for file in $(find . | grep -v "deps/" | grep -v "node_modules/" | grep "./*/lib/" | grep "\.test.*$" | grep "\.${ext}$")
    do
        echo ""
        echo "[test] $file"
        if ! time $prog $file
        then
            exit 1
        fi
    done
}

function main {
    for TASK in $@
    do
        $TASK
    done
}

main $@
