"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const Context = __importStar(require("./context"));
const bodies_of_water_1 = require("../context-examples/bodies-of-water");
const planets_1 = require("../context-examples/planets");
console.log(Context.objs_intent(bodies_of_water_1.bodies_of_water, new Set(["canal", "channel"])));
console.log(Context.objs_closure(bodies_of_water_1.bodies_of_water, new Set(["canal", "channel"])));
console.log(Context.attrs_extent(planets_1.planets, new Set(["size.small"])));
console.log(Context.attrs_extent(planets_1.planets, new Set(["size.medium"])));
console.log(Context.attrs_extent(planets_1.planets, new Set(["size.large"])));
console.log(Context.attrs_extent(planets_1.planets, new Set(["distance-from-sun.far"])));
console.log(Context.attrs_extent(planets_1.planets, new Set(["distance-from-sun.near"])));
console.log(Context.attrs_extent(planets_1.planets, new Set(["moon.no"])));
console.log(Context.attrs_extent(planets_1.planets, new Set(["moon.yes"])));
